package com.example.ui.localization

import androidx.compose.runtime.compositionLocalOf

/**
 * Data model for all UI strings across the application.
 */
data class AppStrings(
    // Common / Global
    val appName: String,
    val appSubtitle: String,
    val versionTag: String,
    val globalDqs: String,
    val leadArchitect: String,
    val baselineBadge: String,
    val sqliteWalActive: String,
    val nodesCount: String,
    val testCycleBtn: String,
    val cancel: String,
    val close: String,
    val save: String,
    val back: String,
    val next: String,
    val confirm: String,
    val resolve: String,
    val delete: String,
    val error: String,
    val success: String,
    val statusDraft: String,
    val statusInReview: String,
    val statusApproved: String,
    val statusRejected: String,

    // Language Selector
    val languagePill: String,
    val languageDialogTitle: String,
    val languageDialogDesc: String,
    val languageBengali: String,
    val languageEnglish: String,
    val languageSelectedNotice: String,

    // Header & Firebase Sync Dialog
    val accountDialogTitle: String,
    val accountDialogDesc: String,
    val emailLabel: String,
    val passwordLabel: String,
    val statusLabel: String,
    val btnLoginRestore: String,
    val btnSyncNow: String,
    val btnPurgeDemo: String,
    val syncStatusSyncing: String,
    val syncStatusCloud: String,

    // Settings API Dialog
    val settingsDialogTitle: String,
    val settingsDialogSubtitle: String,
    val settingsLanguageSection: String,
    val apiModeSection: String,
    val externalApiToggle: String,
    val externalApiToggleDesc: String,
    val apiKeyLabel: String,
    val endpointLabel: String,
    val modelLabel: String,
    val btnTestConnection: String,
    val btnSaveSettings: String,
    val testingConnection: String,
    val connectionSuccess: String,
    val connectionFailed: String,
    val apiModeCustom: String,
    val apiModeOffline: String,
    val apiModeConfig: String,

    // Vault DAG Screen
    val branchLabel: String,
    val btnNewDecision: String,
    val deadlockDetectedTitle: String,
    val deadlockDetectedDesc: String,
    val btnResolveCycle: String,
    val rippleEffectTitle: String,
    val rippleEffectDesc: String,
    val workspaceDecisionsTitle: String,
    val emptyDecisionsPrompt: String,
    val btnWarRoom: String,
    val btnBlueprint: String,
    val btnForkTimeline: String,
    val btnWhatIf: String,
    val searchDecisionsPlaceholder: String,
    val confidenceDqs: String,
    val riskFactor: String,
    val businessImpact: String,

    // Intake & Framing Screen
    val intakeHeader: String,
    val intakeSubtitle: String,
    val decisionTitleLabel: String,
    val decisionTitlePlaceholder: String,
    val problemStatementLabel: String,
    val problemStatementPlaceholder: String,
    val riskLevelLabel: String,
    val businessImpactLabel: String,
    val reversibilityLabel: String,
    val budgetEffortLabel: String,
    val realtimeComplexityLabel: String,
    val taxonomyTagsSection: String,
    val tagFact: String,
    val tagBizConstraint: String,
    val tagTechConstraint: String,
    val tagWish: String,
    val addTagPlaceholder: String,
    val btnAddTag: String,
    val d3ChecklistTitle: String,
    val d3ChecklistSubtitle: String,
    val checkScope: String,
    val checkFocusArea: String,
    val checkConstraints: String,
    val checkGoals: String,
    val btnCompleteFraming: String,
    val btnLaunchProtocol: String,
    val titleProblemRequiredError: String,

    // War Room Screen
    val warRoomHeader: String,
    val warRoomSubtitle: String,
    val roundLabel: String,
    val debatingInProgress: String,
    val stopRuleTriggeredTitle: String,
    val stopRuleTriggeredDesc: String,
    val perspectiveOptimist: String,
    val perspectivePessimist: String,
    val perspectiveRealist: String,
    val perspectiveGovernance: String,
    val redTeamCritiqueTitle: String,
    val qualityVectorTitle: String,
    val btnAdvanceRound: String,
    val btnProceedToBlueprint: String,
    val btnOpenSmartQuery: String,

    // Smart Query Modal
    val smartQueryTitle: String,
    val smartQueryDesc: String,
    val resolutionChoiceLabel: String,
    val resolutionNotePlaceholder: String,
    val btnSubmitResolution: String,

    // Blueprint Studio Screen
    val blueprintHeader: String,
    val blueprintSubtitle: String,
    val lensExecutive: String,
    val lensArchitecture: String,
    val lensUx: String,
    val lensDeveloper: String,
    val lensGovernance: String,
    val finalCertificateTitle: String,
    val sha256SignatureLabel: String,
    val ceoGateTitle: String,
    val ceoGateDesc: String,
    val btnSignApproveCeo: String,
    val statusApprovedNotice: String,
    val executiveSummaryTitle: String,
    val architectureSpecTitle: String,
    val uxFlowTitle: String,
    val devChecklistTitle: String,
    val governanceAuditTitle: String,

    // Fork Timeline Dialog
    val forkDialogTitle: String,
    val forkDialogDesc: String,
    val newBranchNameLabel: String,
    val forkedDecisionTitleLabel: String,
    val btnForkConfirm: String,

    // Cycle Resolution Dialog
    val cycleResolutionTitle: String,
    val cycleResolutionDesc: String,
    val selectEdgeToBreak: String,
    val resolutionNoteLabel: String,
    val btnApplyResolution: String
)

val BengaliStrings = AppStrings(
    // Common / Global
    appName = "NIRZOR KINGMAKER",
    appSubtitle = "মাল্টি-এজেন্ট ডিসিশন ইন্টেলিজেন্স ও আর্কিটেকচারাল ককপিট",
    versionTag = "v7.0 OS",
    globalDqs = "গ্লোবাল DQS",
    leadArchitect = "প্রধান আর্কিটেক্ট: নির্ঝর • RED_TEAM_L3",
    baselineBadge = "v7.0 বেসলাইন",
    sqliteWalActive = "SQLITE WAL: সক্রিয়",
    nodesCount = "নোড: %d",
    testCycleBtn = "+ সাইকেল টেস্ট",
    cancel = "বাতিল",
    close = "বন্ধ করুন",
    save = "সংরক্ষণ করুন",
    back = "ফিরে যান",
    next = "পরবর্তী",
    confirm = "নিশ্চিত করুন",
    resolve = "সমাধান করুন",
    delete = "মুছে ফেলুন",
    error = "ত্রুটি",
    success = "সফল",
    statusDraft = "খসড়া (DRAFT)",
    statusInReview = "পর্যালোচনাধীন (IN_REVIEW)",
    statusApproved = "অনুমোদিত (APPROVED)",
    statusRejected = "প্রত্যাখ্যাত (REJECTED)",

    // Language Selector
    languagePill = "ভাষা: বাংলা",
    languageDialogTitle = "ভাষা নির্বাচন করুন / Select Language",
    languageDialogDesc = "অ্যাপ্লিকেশনের ভাষা পরিবর্তন করুন। বাংলা ডিফল্ট হিসেবে সেট করা আছে।",
    languageBengali = "বাংলা (ডিফল্ট)",
    languageEnglish = "English",
    languageSelectedNotice = "ভাষা পরিবর্তন সফলভাবে সম্পন্ন হয়েছে",

    // Header & Firebase Sync Dialog
    accountDialogTitle = "ফায়ারবেস ক্লাউড সিঙ্ক ও অ্যাকাউন্ট",
    accountDialogDesc = "লগইন করা অ্যাকাউন্ট অনুযায়ী Firestore থেকে শেষ সংরক্ষিত অবস্থা, ব্রাঞ্চ ও অডিট হিস্ট্রি পুনরুদ্ধার করা হবে।",
    emailLabel = "অ্যাকাউন্ট ইমেইল",
    passwordLabel = "পাসওয়ার্ড",
    statusLabel = "স্ট্যাটাস:",
    btnLoginRestore = "লগইন ও পুনরুদ্ধার",
    btnSyncNow = "এখনই সিঙ্ক করুন",
    btnPurgeDemo = "ডেমো মুছুন",
    syncStatusSyncing = "সিঙ্ক হচ্ছে...",
    syncStatusCloud = "ক্লাউড",

    // Settings API Dialog
    settingsDialogTitle = "এআই ইঞ্জিন ও এপিআই সেটিংস",
    settingsDialogSubtitle = "অফলাইন ডিটারমিনিস্টিক ও বাহ্যিক এপিআই কনফিগারেশন",
    settingsLanguageSection = "অ্যাপের ভাষা (App Language)",
    apiModeSection = "এআই ইঞ্জিন মোড",
    externalApiToggle = "বাহ্যিক এআই এপিআই সক্রিয় করুন",
    externalApiToggleDesc = "সক্রিয় থাকলে সরাসরি Gemini API কল হবে, অন্যথায় অফলাইন হাই-কনফিডেন্স ইঞ্জিন কাজ করবে।",
    apiKeyLabel = "এপিআই কী (API Key)",
    endpointLabel = "কাস্টম এন্ডপয়েন্ট",
    modelLabel = "নির্বাচিত মডেল",
    btnTestConnection = "সংযোগ পরীক্ষা করুন",
    btnSaveSettings = "সেটিংস সংরক্ষণ করুন",
    testingConnection = "সংযোগ পরীক্ষা চলছে...",
    connectionSuccess = "সংযোগ সফল হয়েছে!",
    connectionFailed = "সংযোগ ব্যর্থ হয়েছে!",
    apiModeCustom = "API: কাস্টম",
    apiModeOffline = "API: অফলাইন",
    apiModeConfig = "API: কনফিগ",

    // Vault DAG Screen
    branchLabel = "সক্রিয় ব্রাঞ্চ:",
    btnNewDecision = "+ নতুন সিদ্ধান্ত গ্রহণ",
    deadlockDetectedTitle = "সাইক্লিক ডেডলক সনাক্ত হয়েছে!",
    deadlockDetectedDesc = "ডিপেন্ডেন্সি গ্রাফে লুপ বা ডেডলক সনাক্ত হয়েছে। সমাধানের জন্য নিচের টাস্কে অ্যাকশন নিন।",
    btnResolveCycle = "সাইকেল সমাধান করুন",
    rippleEffectTitle = "রিপল এফেক্ট বিশ্লেষণ",
    rippleEffectDesc = "নির্বাচিত নোডের পরিবর্তনের প্রভাব ডিপেন্ডেন্ট সকল নোডে পর্যবেক্ষণ করুন।",
    workspaceDecisionsTitle = "ওয়ার্কস্পেস সিদ্ধান্ত পাইপলাইন",
    emptyDecisionsPrompt = "এই ব্রাঞ্চে কোনো সিদ্ধান্ত নোড নেই। নতুন সিদ্ধান্ত তৈরি করতে নিচের বাটনে চাপ দিন।",
    btnWarRoom = "ওয়ার রুম",
    btnBlueprint = "ব্লুপ্রিন্ট",
    btnForkTimeline = "টাইমলাইন ফর্ক",
    btnWhatIf = "কী-যদি সিমুলেশন",
    searchDecisionsPlaceholder = "সিদ্ধান্ত অনুসন্ধান করুন...",
    confidenceDqs = "কনফিডেন্স DQS",
    riskFactor = "ঝুঁকি",
    businessImpact = "প্রভাব",

    // Intake & Framing Screen
    intakeHeader = "D1-D3 ইনটেক ও ফ্রেমিং স্টুডিও",
    intakeSubtitle = "সমস্যা প্রণয়ন, জটিলতা বিশ্লেষণ ও ডি৩ নিশ্চিতকরণ গেট",
    decisionTitleLabel = "সিদ্ধান্তের শিরোনাম",
    decisionTitlePlaceholder = "যেমন: মাইক্রোসার্ভিসেস আর্কিটেকচার মাইগ্রেশন ২০২৬",
    problemStatementLabel = "সমস্যার মূল বিবৃতি ও প্রেক্ষাপট",
    problemStatementPlaceholder = "সমস্যাটির বিস্তারিত প্রেক্ষাপট, বর্তমান চ্যালেঞ্জ এবং সিদ্ধান্তের মূল উদ্দেশ্য বর্ণনা করুন...",
    riskLevelLabel = "ঝুঁকির মাত্রা (Risk Level):",
    businessImpactLabel = "ব্যবসায়িক প্রভাব (Business Impact):",
    reversibilityLabel = "পরিবর্তনযোগ্যতা (Reversibility):",
    budgetEffortLabel = "বাজেট ও রিসোর্স এফোর্ট:",
    realtimeComplexityLabel = "রিয়েলটাইম জটিলতা স্কোর:",
    taxonomyTagsSection = "ট্যাক্সোনমি ট্যাগসমূহ",
    tagFact = "তথ্য (Fact)",
    tagBizConstraint = "ব্যবসায়িক বাধা",
    tagTechConstraint = "প্রযুক্তিগত বাধা",
    tagWish = "আকাঙ্ক্ষা (Wish)",
    addTagPlaceholder = "নতুন ট্যাগ লিখুন...",
    btnAddTag = "+ ট্যাগ যোগ",
    d3ChecklistTitle = "D3 নিশ্চিতকরণ চেকলিস্ট (হিউম্যান-ইন-দ্য-লুপ গেট)",
    d3ChecklistSubtitle = "ওয়ার রুমে যাওয়ার পূর্বে চারটি কোর পয়েন্ট নিশ্চিত করতে হবে:",
    checkScope = "১. স্কোপ ও পরিধি সম্পূর্ণ স্পষ্ট ও সংজ্ঞায়িত",
    checkFocusArea = "২. মূল ফোকাস এলাকা ও অগ্রাধিকার চিহ্নিত",
    checkConstraints = "৩. টেকনিক্যাল ও বিজনেস সীমাবদ্ধতা খতিয়ে দেখা হয়েছে",
    checkGoals = "৪. চূড়ান্ত সাফল্যের মাপকাঠি ও গোল নিশ্চিত",
    btnCompleteFraming = "D2 ফ্রেমিং সম্পন্ন করুন",
    btnLaunchProtocol = "মাল্টি-এজেন্ট প্রটোকল চালু করুন",
    titleProblemRequiredError = "দয়া করে শিরোনাম এবং সমস্যার বিবরণ পূরণ করুন!",

    // War Room Screen
    warRoomHeader = "D4-D5 মাল্টি-এজেন্ট ওয়ার রুম",
    warRoomSubtitle = "স্বায়ত্তশাসিত অপটিমিস্ট, পেসিমিস্ট, রিয়্যালিস্ট ও রেড টিম বিতর্ক",
    roundLabel = "বিতর্ক রাউন্ড: %d",
    debatingInProgress = "এজেন্টদের বিতর্ক ও গভীর বিশ্লেষণ চলমান...",
    stopRuleTriggeredTitle = "স্টপ রুল কার্যকর হয়েছে!",
    stopRuleTriggeredDesc = "এজেন্টদের ঐক্যমত্য সূচক থ্রেশহোল্ড অতিক্রম করেছে। পরবর্তী ধাপে যাওয়া নিরাপদ।",
    perspectiveOptimist = "আশাবাদী দৃষ্টিভঙ্গি (Optimist)",
    perspectivePessimist = "সংশয়বাদী দৃষ্টিভঙ্গি (Pessimist)",
    perspectiveRealist = "বাস্তববাদী দৃষ্টিভঙ্গি (Realist)",
    perspectiveGovernance = "গভর্নেন্স ও সিকিউরিটি দৃষ্টিভঙ্গি",
    redTeamCritiqueTitle = "রেড টিম ক্রিটিক ও স্ট্রেস টেস্ট",
    qualityVectorTitle = "কোয়ালিটি ভেক্টর ও DQS মেট্রিক্স",
    btnAdvanceRound = "পরবর্তী রাউন্ডে এগিয়ে যান",
    btnProceedToBlueprint = "ব্লুপ্রিন্ট স্টুডিওতে যান",
    btnOpenSmartQuery = "স্মার্ট কোয়েরি সমাধান",

    // Smart Query Modal
    smartQueryTitle = "স্মার্ট কোয়েরি ট্রেড-অফ সমাধান",
    smartQueryDesc = "দ্বন্দ্বমূলক সিদ্ধান্তের ক্ষেত্রে মানব সিদ্ধান্তকারীর হস্তক্ষেপ ও মতামত প্রয়োজন।",
    resolutionChoiceLabel = "সমাধানের বিকল্প নির্বাচন করুন",
    resolutionNotePlaceholder = "সিদ্ধান্তের পেছনে আপনার কারণ বা কৌশলগত নোট লিখুন...",
    btnSubmitResolution = "সমাধান জমা দিন ও আপডেট করুন",

    // Blueprint Studio Screen
    blueprintHeader = "D6-D7 ব্লুপ্রিন্ট স্টুডিও ও সিইও গেট",
    blueprintSubtitle = "৫-লেন্স সমন্বয়, চূড়ান্ত রিভিউ প্যাকেট ও ডিজিটাল স্বাক্ষর",
    lensExecutive = "এক্সিকিউটিভ",
    lensArchitecture = "আর্কিটেকচার",
    lensUx = "ইউজার এক্সপেরিয়েন্স",
    lensDeveloper = "ডেভেলপার",
    lensGovernance = "গভর্নেন্স",
    finalCertificateTitle = "চূড়ান্ত সিদ্ধান্ত অনুমোদন সনদ",
    sha256SignatureLabel = "ডিজিটাল সিগনেচার হ্যাশ (SHA-256):",
    ceoGateTitle = "সিইও অনুমোদন গেট (CEO Gate Attestation)",
    ceoGateDesc = "এই সিদ্ধান্তে স্বাক্ষর প্রদান করলে এটি চূড়ান্তভাবে অনুমোদিত হিসেবে অপরিবর্তনীয় SQLite WAL লেজারে সিলমোহরকৃত হবে।",
    btnSignApproveCeo = "সিইও হিসেবে স্বাক্ষর ও চূড়ান্ত অনুমোদন দিন",
    statusApprovedNotice = "এই সিদ্ধান্তটি ইতোমধ্যে সিইও কর্তৃক অনুমোদিত ও ক্রিপ্টোগ্রাফিক্যালি সিলমোহরকৃত।",
    executiveSummaryTitle = "এক্সিকিউটিভ সামারি ও ব্যবসায়িক যৌক্তিকতা",
    architectureSpecTitle = "সিস্টেম আর্কিটেকচার ও টেকনিক্যাল স্পেসিফিকেশন",
    uxFlowTitle = "ইউএক্স ডিজাইন ইমপ্যাক্ট ও ইউজার জার্নি",
    devChecklistTitle = "ডেভেলপার ইমপ্লিমেন্টেশন চেকলিস্ট",
    governanceAuditTitle = "গভর্নেন্স কমপ্লায়েন্স ও অডিট ট্রেইল",

    // Fork Timeline Dialog
    forkDialogTitle = "নতুন টাইমলাইন ব্রাঞ্চ ফর্ক করুন",
    forkDialogDesc = "একটি বিকল্প সিদ্ধান্তের পথ অন্বেষণ করতে মূল টাইমলাইন থেকে একটি নতুন ব্রাঞ্চ তৈরি করুন।",
    newBranchNameLabel = "নতুন ব্রাঞ্চের নাম (যেমন: experiment/edge-first)",
    forkedDecisionTitleLabel = "ফর্ককৃত সিদ্ধান্তের নতুন শিরোনাম",
    btnForkConfirm = "টাইমলাইন ফর্ক করুন",

    // Cycle Resolution Dialog
    cycleResolutionTitle = "সাইক্লিক ডিপেন্ডেন্সি সমাধান",
    cycleResolutionDesc = "ডিপেন্ডেন্সি চক্র ভাঙতে একটি সংযোগ বিচ্ছিন্ন করুন অথবা রদবদল করুন।",
    selectEdgeToBreak = "কোন এজটি বিচ্ছিন্ন করবেন?",
    resolutionNoteLabel = "সমাধানের কারণ বা ব্যাখ্যা",
    btnApplyResolution = "সমাধান প্রয়োগ করুন"
)

val EnglishStrings = AppStrings(
    // Common / Global
    appName = "NIRZOR KINGMAKER",
    appSubtitle = "Multi-Agent Decision Intelligence OS & Architectural Cockpit",
    versionTag = "v7.0 OS",
    globalDqs = "GLOBAL DQS",
    leadArchitect = "LEAD ARCHITECT: NIRZOR • RED_TEAM_L3",
    baselineBadge = "v7.0 BASELINE",
    sqliteWalActive = "SQLITE WAL: ACTIVE",
    nodesCount = "NODES: %d",
    testCycleBtn = "+ TEST CYCLE",
    cancel = "Cancel",
    close = "Close",
    save = "Save",
    back = "Back",
    next = "Next",
    confirm = "Confirm",
    resolve = "Resolve",
    delete = "Delete",
    error = "Error",
    success = "Success",
    statusDraft = "DRAFT",
    statusInReview = "IN_REVIEW",
    statusApproved = "APPROVED",
    statusRejected = "REJECTED",

    // Language Selector
    languagePill = "Lang: English",
    languageDialogTitle = "Select Language / ভাষা নির্বাচন",
    languageDialogDesc = "Switch the application language. Bengali is set as the default.",
    languageBengali = "বাংলা (ডিফল্ট / Default)",
    languageEnglish = "English",
    languageSelectedNotice = "Language changed successfully",

    // Header & Firebase Sync Dialog
    accountDialogTitle = "FIREBASE CLOUD SYNC & ACCOUNT",
    accountDialogDesc = "Restore the last saved state, branches, and audit history from Firestore based on the logged-in account.",
    emailLabel = "Account Email",
    passwordLabel = "Password",
    statusLabel = "Status:",
    btnLoginRestore = "LOGIN & RESTORE STATE",
    btnSyncNow = "SYNC NOW",
    btnPurgeDemo = "PURGE DEMO",
    syncStatusSyncing = "SYNC...",
    syncStatusCloud = "CLOUD",

    // Settings API Dialog
    settingsDialogTitle = "AI ENGINE & API SETTINGS",
    settingsDialogSubtitle = "Offline deterministic vs external API key configuration",
    settingsLanguageSection = "App Language",
    apiModeSection = "AI Engine Mode",
    externalApiToggle = "Enable External AI API Key",
    externalApiToggleDesc = "When enabled, live Gemini API calls are executed; otherwise the offline high-confidence engine operates.",
    apiKeyLabel = "API Key",
    endpointLabel = "Custom Endpoint",
    modelLabel = "Selected Model",
    btnTestConnection = "TEST CONNECTION",
    btnSaveSettings = "SAVE SETTINGS",
    testingConnection = "Testing connection...",
    connectionSuccess = "Connection successful!",
    connectionFailed = "Connection failed!",
    apiModeCustom = "API: CUSTOM",
    apiModeOffline = "API: OFFLINE",
    apiModeConfig = "API: CONFIG",

    // Vault DAG Screen
    branchLabel = "Active Branch:",
    btnNewDecision = "+ NEW DECISION STREAM",
    deadlockDetectedTitle = "CYCLIC DEADLOCK DETECTED!",
    deadlockDetectedDesc = "A dependency cycle has been detected in the DAG. Take action using the resolution card below.",
    btnResolveCycle = "RESOLVE CYCLE",
    rippleEffectTitle = "RIPPLE EFFECT ANALYSIS",
    rippleEffectDesc = "Observe ripple impact on downstream and upstream connected decision nodes.",
    workspaceDecisionsTitle = "Workspace Decision Pipeline",
    emptyDecisionsPrompt = "No decision nodes in this branch. Tap the button below to initialize a new decision.",
    btnWarRoom = "WAR ROOM",
    btnBlueprint = "BLUEPRINT",
    btnForkTimeline = "FORK TIMELINE",
    btnWhatIf = "WHAT-IF SIMULATION",
    searchDecisionsPlaceholder = "Search decisions...",
    confidenceDqs = "Confidence DQS",
    riskFactor = "Risk",
    businessImpact = "Impact",

    // Intake & Framing Screen
    intakeHeader = "D1-D3 INTAKE & FRAMING STUDIO",
    intakeSubtitle = "Problem Formulation, Real-time Complexity & D3 Gate",
    decisionTitleLabel = "Decision Title",
    decisionTitlePlaceholder = "e.g. Microservices Architecture Migration 2026",
    problemStatementLabel = "Core Problem Statement & Context",
    problemStatementPlaceholder = "Describe context, primary challenges, and strategic objectives...",
    riskLevelLabel = "Risk Level:",
    businessImpactLabel = "Business Impact:",
    reversibilityLabel = "Reversibility:",
    budgetEffortLabel = "Budget & Resource Effort:",
    realtimeComplexityLabel = "Real-time Complexity Score:",
    taxonomyTagsSection = "Taxonomy Tags",
    tagFact = "Fact",
    tagBizConstraint = "Business Constraint",
    tagTechConstraint = "Technical Constraint",
    tagWish = "Wish",
    addTagPlaceholder = "Type a new tag...",
    btnAddTag = "+ Add Tag",
    d3ChecklistTitle = "D3 Confirmation Gate (Human-in-the-Loop)",
    d3ChecklistSubtitle = "Verify the four core criteria before proceeding to the War Room:",
    checkScope = "1. Scope and boundaries are clearly defined",
    checkFocusArea = "2. Core focus areas and priorities identified",
    checkConstraints = "3. Technical and business constraints reviewed",
    checkGoals = "4. Final success metrics and goals confirmed",
    btnCompleteFraming = "COMPLETE D2 FRAMING",
    btnLaunchProtocol = "LAUNCH MULTI-AGENT PROTOCOL",
    titleProblemRequiredError = "Please fill in both title and problem statement!",

    // War Room Screen
    warRoomHeader = "D4-D5 MULTI-AGENT WAR ROOM",
    warRoomSubtitle = "Autonomous Optimist, Pessimist, Realist & Red Team Debate",
    roundLabel = "Debate Round: %d",
    debatingInProgress = "Multi-agent debate and deep analysis in progress...",
    stopRuleTriggeredTitle = "STOP RULE TRIGGERED!",
    stopRuleTriggeredDesc = "Agent consensus threshold has been met. Safe to proceed to synthesis.",
    perspectiveOptimist = "Optimist Perspective",
    perspectivePessimist = "Pessimist Perspective",
    perspectiveRealist = "Realist Perspective",
    perspectiveGovernance = "Governance & Security Perspective",
    redTeamCritiqueTitle = "Red Team Critique & Stress Test",
    qualityVectorTitle = "Quality Vector & DQS Metrics",
    btnAdvanceRound = "ADVANCE NEXT ROUND",
    btnProceedToBlueprint = "PROCEED TO BLUEPRINT",
    btnOpenSmartQuery = "SMART QUERY RESOLUTION",

    // Smart Query Modal
    smartQueryTitle = "Smart Query Trade-off Resolution",
    smartQueryDesc = "Human intervention required to reconcile contradictory perspectives.",
    resolutionChoiceLabel = "Select Trade-off Resolution",
    resolutionNotePlaceholder = "Enter strategic reasoning or rationale...",
    btnSubmitResolution = "SUBMIT RESOLUTION & UPDATE",

    // Blueprint Studio Screen
    blueprintHeader = "D6-D7 BLUEPRINT STUDIO & CEO GATE",
    blueprintSubtitle = "5-Lens Synthesis, Review Packet & Digital Signature",
    lensExecutive = "Executive",
    lensArchitecture = "Architecture",
    lensUx = "User Experience",
    lensDeveloper = "Developer",
    lensGovernance = "Governance",
    finalCertificateTitle = "Finalization Certificate",
    sha256SignatureLabel = "Digital Signature Hash (SHA-256):",
    ceoGateTitle = "CEO Gate Attestation (Human-in-the-Loop)",
    ceoGateDesc = "Signing will permanently commit this decision into the immutable SQLite WAL event ledger.",
    btnSignApproveCeo = "SIGN & APPROVE AS CEO",
    statusApprovedNotice = "This decision is already sealed and approved by the CEO.",
    executiveSummaryTitle = "Executive Summary & Business Rationale",
    architectureSpecTitle = "System Architecture & Technical Specs",
    uxFlowTitle = "UX Impact & User Journey",
    devChecklistTitle = "Developer Implementation Checklist",
    governanceAuditTitle = "Governance Compliance & Audit Trail",

    // Fork Timeline Dialog
    forkDialogTitle = "Fork New Timeline Branch",
    forkDialogDesc = "Create an alternate branch to explore counter-factual decision paths.",
    newBranchNameLabel = "Branch Name (e.g. experiment/edge-first)",
    forkedDecisionTitleLabel = "Forked Decision Title",
    btnForkConfirm = "FORK TIMELINE",

    // Cycle Resolution Dialog
    cycleResolutionTitle = "Cyclic Dependency Resolution",
    cycleResolutionDesc = "Break an edge or reorder dependencies to resolve the graph cycle.",
    selectEdgeToBreak = "Select edge to disconnect:",
    resolutionNoteLabel = "Resolution Rationale",
    btnApplyResolution = "APPLY RESOLUTION"
)

fun getAppStrings(language: AppLanguage): AppStrings {
    return when (language) {
        AppLanguage.BN -> BengaliStrings
        AppLanguage.EN -> EnglishStrings
    }
}

val LocalAppLanguage = compositionLocalOf { AppLanguage.DEFAULT }
val LocalAppStrings = compositionLocalOf { BengaliStrings }
